### PR TITLE
Upgrade plugin with latest changes

### PR DESCRIPTION
**Pull request by renatonascalves**
- Run GH action on the `master` branch.
- Bump some GH actions packages
- Test against PHP 8.1
- Let `yoast/phpunit-polyfills` decide which PHPUnit version to install based on the current PHP version

### CODE REVIEW

**Comment by renatonascalves** [comment]
@imath I don't have permission to do that, but could update the branch protection rules to allow merging on `master` only if the GH actions passes?

**Comment by imath** [comment]
@renatonascalves sure but can you guide me on doing so as I don't see how to make it possible 😬. It looks like we need to use the status checks thing but it's unclear how to set this up!
Capture d’écran 2022-08-15 à 11 42 24
When I search for status checks of the last week I get no results 😞

**Comment by renatonascalves** [comment]
Weird. So when you search for WP: 6.0 or PHPCS you get no actions?

**Comment by imath** [comment]
Thanks for your help, here's what I get, should I select all ?
Capture d’écran 2022-08-15 à 14 13 16

**Comment by renatonascalves** [comment]
IMO, all but 8.1.

**Comment by imath** [comment]
Ok, just did it!

**Review by imath — APPROVED** [review]
Looks good! Thanks for your work on it 👍

**Pull request merged**
