### PR TITLE
Install correct version of PHP on Travis.

### PR DESCRIPTION
**Pull request by boonebgorges**
i think this will fix the failing TravisCI build - opening a PR so that we can get a build running

### CODE REVIEW

**Comment by boonebgorges** [comment]
Gah. Giving up for now.

**Comment by boonebgorges** [comment]
@dcavins I'm beginning to feel that way.

**Comment by renatonascalves** [comment]
I know, it is hard! Until it isn't.

**Comment by boonebgorges** [comment]
Green!

**Comment by renatonascalves** [comment]
Wow! Thank you @boonebgorges

**Pull request merged**
