### PR TITLE
Group READABLE endpoint

### PR DESCRIPTION
**Pull request by dcavins**
First pass at allowing fetching of groups using REST. Fetches single
groups and collections of groups using an argument format much like
`groups_get_groups()`.

Still need to work out accepting meta arguments and also visibility of hidden groups.

How are we going to test all of this REST stuff?

Finally, is the REST `context` parameter really a security thing? It appears to be used that way in the main plugin, but I'm doubtful. I've used it here to make `populate_extras` only be possible with the context elevation, but it's still really a view context with increased user permissions, so maybe that's incorrect.

### CODE REVIEW

**Comment by BronsonQuick** [comment]
Awesome! Thanks for making a start on this!

>How are we going to test all of this REST stuff?

I originally had Travis for this but @paulgibbs chose to remove it: 
https://github.com/buddypress/BP-REST/commit/0ee3de4df79005dc48d55b01df36c331f8180c20

>Finally, is the REST `context` parameter really a security thing?

I believe it's to do with roles and permissions.

**Comment by paulgibbs** [comment]
Don't know about testing yet. Going to talk to Boone and John this Monday and we'll come up with a proposal.

`context` is used as a way of managing fields returned with objects on certain endpoints, for any reason. It's not meant to manage any kind of privileged data access. Generally, it seems pretty situation specific, and I don't think we need to use it until we find somewhere it'd help.

**Comment by cezarneaga** [comment]
`wp-json/buddypress/v1/groups` doesn't work for me. does it work for you?

**Comment by renatonascalves** [comment]
@cezarneaga Could you elaborate on how it doesn't work for you? Do you see any errors?

**Comment by cezarneaga** [comment]
sorry. no errors just an empty array. groups/[id] works fine though

**Comment by renatonascalves** [comment]
Thank you @dcavins 

I reviewed your PR and fixed what's necessary. This is good to merge!
I'll add the unit tests later. :)

**Pull request merged**
