### PR TITLE
added filter for activity data

### PR DESCRIPTION
**Pull request by satheshk385**
added filter to change activity data, because we can't filter activity response data

### CODE REVIEW

**Comment by renatonascalves** [comment]
@satheshk385 Have you tried using this hook? https://github.com/buddypress/BP-REST/blob/28dda16881232769b4cef3b9fa2f901e1492c819/includes/bp-activity/classes/class-bp-rest-activity-endpoint.php#L969

You can filter the information via the `bp_rest_activity_prepare_value` hook...

**Comment by satheshk385** [comment]
@renatonascalves 
I have tried, But we can't add data in that $response variable.

checkout the class reference of $response object
https://developer.wordpress.org/reference/classes/wp_rest_response/
https://developer.wordpress.org/reference/classes/wp_rest_response/

**Comment by satheshk385** [comment]
@renatonascalves 
you are right we can filter data
$response->get_data();
$response->set_data();
https://developer.wordpress.org/reference/classes/wp_http_response/

**Comment by renatonascalves** [comment]
:)

**Pull request closed without merging**
