### PR TITLE
Members: Only query for fields when necessary

### PR DESCRIPTION
**Pull request by r-a-y**
The WP REST API has a global `'_fields'` parameter allowing consumers of the API to restrict the response to only properties specified in `'_fields'`: https://developer.wordpress.org/rest-api/using-the-rest-api/global-parameters/#_fields

We should check this parameter before querying for any member properties in the `BP_REST_Members_Endpoint::user_data()` method: https://github.com/buddypress/BP-REST/blob/02d3de0ee278c52a80c2f77a272b9af1b079f4d6/includes/bp-members/classes/class-bp-rest-members-endpoint.php#L482

For example, if we perform the following BP Members API request: `example.com/wp-json/buddypress/v1/members/?_fields=id,name,user_login,link`, this shouldn't query other member fields like `'xprofile'`, `'friendship_status'`, etc. This can dramatically speed up the response time for the Members endpoint when the `'_fields'` global parameter is used.

From some local testing, this can speed up the Members endpoint by 50% or more. The main offender is the `'xprofile'` field. We should probably do the same  approach for our other endpoints as well where necessary, but there will not be as significant gains compared to the Members endpoint.

### CODE REVIEW

**Review by renatonascalves — APPROVED** [review]
I like this enhacement and feel the rest of the endpoints could benefit from it. I only don't like the implementation of it. But I'm not sure how core is doing it.

For this pull request, it is okay. :)

**Comment by renatonascalves** [comment]
@r-a-y Could you fix this phpcs issue?

**Comment by r-a-y** [comment]
> @r-a-y Could you fix this phpcs issue?

Done. I used `phpcbf --standard=WordPress` and that fixed the main short array syntax issue. It also added a bunch of spaces because WordPress loves spaces 😄

**Comment by imath** [comment]
@r-a-y if you have some time, It would be nice to:
`git rebase -i master` to cherry pick commits that are only needed for this PR (after making sure your master branch is even with this repo one).

**Comment by r-a-y** [comment]
> @r-a-y if you have some time, It would be nice to:
git rebase -i master to cherry pick commits that are only needed for this PR (after making sure your master branch is even with this repo one).

Thanks for the pointer about rebasing, imath 👍

I've just done this.

**Review by imath — APPROVED** [review]
Looks good! Thanks a lot @r-a-y 💪

**Pull request merged**
