### PR TITLE
BuddyPress Members EndPoint Class Structure.

### PR DESCRIPTION
**Pull request by chetansatasiya**
* 70% of get_items methods code
* Member Endpoint Supports Member Types.

### CODE REVIEW

**Comment by singhleo** [comment]
Finished Basic GET and Single Get

**Comment by singhleo** [comment]
Added Delete Method 
This is being redirected to WordPress default user API.

**Comment by renatonascalves** [comment]
I won't merge this but I'll use bits of it for a new version!  Thanks, @singhleo, and @chetansatasiya for your fine work here! :)

**Comment by singhleo** [comment]
👍🏼  I will glad if single line been useful for you :) .. let me know if need my help.

**Pull request closed without merging**
